#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/hendemd/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/hendemd/neuron/nrn/i686/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/hendemd/neuron/i686/.libs/libnrnmech.so" "$@"
